//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Пр.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class datgVieW
    {
        public System.DateTime record_date { get; set; }
        public Nullable<double> world_rec { get; set; }
        public string Sport_name { get; set; }
        public string unit_of_meas { get; set; }
        public string FIO { get; set; }
        public Nullable<int> age { get; set; }
        public int id_Athletes { get; set; }
    }
}
