//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Пр.Classes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class wholesaleEntities4 : DbContext
    {
        public wholesaleEntities4()
            : base("name=wholesaleEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Athletes> Athletes { get; set; }
        public virtual DbSet<Sport> Sport { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
        public virtual DbSet<datgVieW> datgVieW { get; set; }
    }
}
